apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hello-gateway

spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same

    - name: websecure
      protocol: HTTPS
      port: 443
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: hello-gateway-tls
      allowedRoutes:
        namespaces:
          from: Same
