apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-httproute
  namespace: hello

spec:
  parentRefs:
  - name: hello-gateway
    sectionName: https
    kind: Gateway
    namespace: hello

  hostnames:
  - hello.com

  rules:
  - backendRefs:
    - name: hello-svc
      port: 3000
