apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-httproute

spec:
  parentRefs:
  - name: hello-gateway
    sectionName: websecure
    kind: Gateway
    namespace: hello

  hostnames:
  - dev.hello.com

  rules:
  - backendRefs:
    - name: hello-svc
      port: 3000
    matches:
      - path:
          type: PathPrefix
          value: /
