apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello
    service: hello
    k8s-app: hello
spec:
  ports:
    - name: hello-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: hello

